psql srdb -f ../spreadsheets/RICARD-PERUVIANANCHOVETA-1963-2004-editedDR.sql
psql srdb -f ../spreadsheets/Fulton-bight_redfish-australia-2007_v2-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/Fulton-east-ling-australia-2007_v2-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/Fulton-west-ling-australia-2007_v2-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/Fulton-cascade_orange_roughy-australia-2007_v2-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/Fulton-east_orange_roughy-australia-2007_v2-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/Fulton-morwong-australia-2007_v2-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/Fulton-tiger_flathead-australia-2007_v2-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/Fulton-brown_tiger_prawn-australia-2007_v2-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/Fulton-grooved_tiger_prawn-australia-2007_v2-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/Fulton-deepwater_flathead-australia-2007_v2-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-TASGIANTCRAB-2008-editedDR.sql
psql srdb -f ../spreadsheets/Fulton-east-gemfish-australia-2007_v2-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/Fulton-east_blue_warehou-australia-2007_v2-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/Fulton-west_blue_warehou-australia-2007_v2-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/Fulton-silver_warehou-australia-2007_v2-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/Fulton-whiting-australia-2007_v2-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-TOOTHFISHRS-2007-v2-editedDR.sql
psql srdb -f ../spreadsheets/Parma-ANCHOVY-ARG-S-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/Parma-ANCHOVY-ARG-N-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/Parma-POLACA-ARG-S-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/Parma-AHAKE-ARG-S-2009-v2-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/Parma-AHAKE-ARG-N-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/Parma-HOKI-ARG-S-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/PREFONTAINE-HAD5Zejm-2003-editedDR-jbQAQC.sql
psql srdb -f ../spreadsheets/PREFONTAINE-HERR4TFA-2007-editedRP-QAQC.sql
psql srdb -f ../spreadsheets/PREFONTAINE-HERR4TSP-2007-editedRP-QAQC.sql
psql srdb -f ../spreadsheets/PREFONTAINE-HERR4RFA-2004-editedRP-QAQC.sql
psql srdb -f ../spreadsheets/PREFONTAINE-HERR4RSP-2004-editedRP-QAQC.sql
psql srdb -f ../spreadsheets/PREFONTAINE-COD3Pn4RS-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/PREFONTAINE-GHAL01ABCDEF-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/PREFONTAINE-MONK2J3KLNOPs-2001-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/PREFONTAINE-WHAKE4VWX5-2005-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/PREFONTAINE-AMPL23K-2003-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/PREFONTAINE-COD4TVn-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/RICARD-COD4TVn-2007-editedDR.sql
psql srdb -f ../spreadsheets/PREFONTAINE-COD3Ps-2004-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/PREFONTAINE-COD4VsW-2003-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/PREFONTAINE-COD5Zjm-2003-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/COLLIE-HERRQCI-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/COLLIE-HERRCC-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/COLLIE-HERRPRD-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/COLLIE-HERRSOG-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/COLLIE-HERRWCVI-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/COLLIE-PCODHS-2005-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/COLLIE-PCODWCVANI-2002-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/Branch-SA-PToothfish-2007-editedOJ.sql
psql srdb -f ../spreadsheets/Branch-SA-Kingklip-2008-editedOJ.sql
psql srdb -f ../spreadsheets/deMoor-SAAnchovy-2007-editedDR.sql
psql srdb -f ../spreadsheets/deMoor-SASardine-2007-editedDR.sql
psql srdb -f ../spreadsheets/Plaganyi-SA-abalone-2008-editedDR.sql
psql srdb -f ../spreadsheets/Johnston-SAWestRockLobster-A1-2-2007-editedDR.sql
psql srdb -f ../spreadsheets/Johnston-SAWestRockLobster-A3-4-2007-editedDR.sql
psql srdb -f ../spreadsheets/Johnston-SAWestRockLobster-A5-6-2007-editedDR.sql
psql srdb -f ../spreadsheets/Johnston-SAWestRockLobster-A7-2007-editedDR.sql
psql srdb -f ../spreadsheets/Johnston-SAWestRockLobster-A8-2007-editedDR.sql
psql srdb -f ../spreadsheets/DEDECKER-SA-Mparadoxus-2008-editedDR.sql
psql srdb -f ../spreadsheets/DEDECKER-SA-Mcapensis-2008-editedOJ.sql
psql srdb -f ../spreadsheets/Johnston-SASouthRockLobster-2008-editedDR.sql
psql srdb -f ../spreadsheets/Johnston-SAHorseMackerel-2007-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-YFINEPAC-2006-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-BETEPAC-2007-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-BETWPO-2008-editedDR-OJ-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-BIGEYEATL-2008-editedOJ.sql
psql srdb -f ../spreadsheets/JENSEN-SKJEATL-2008-editedOJ.sql
psql srdb -f ../spreadsheets/JENSEN-SKJWATL-2008-editedOJ.sql
psql srdb -f ../spreadsheets/JENSEN-YFINATL-2008-editedOJ.sql
psql srdb -f ../spreadsheets/WORM-ALBANATL-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/WORM-ATBTUNAEATL-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/WORM-ATBTUNAWATL-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-SWORDSATL-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-SWORDNATL-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-SWORDMED-2007-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-BIGEYEIO-2007-editedDR.sql
psql srdb -f ../spreadsheets/MINTO-SOLENS-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-SOLEVIId-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-HADICE-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-WHITNS-VIId-IIIa-2007-editedDR-QAQC-revised.sql
psql srdb -f ../spreadsheets/MINTO-GOLDREDNEAR-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-CODNORCOAST-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-CODNEAR-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-CAPENOR-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-CODNS-2007-example-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-REDDEEPI-II-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-HERR2224IIIa-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-HADNEAR-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-SPRATNS-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-CAPEICE-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-POLLNEAR-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-HERRNS-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-HERRVIa-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-HERRVIaVIIbc-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-CODFAPL-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-CODICE-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-HADIS-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-HADFAPL-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-WHITVIa-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-CODKAT-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-POLLFAPL-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-CODVIIa-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-CODVIa-2007-editedDR-QAQC-revised.sql
psql srdb -f ../spreadsheets/MINTO-HADVIa-2007-editedDR-QAQC-revised.sql
psql srdb -f ../spreadsheets/MINTO-PLAICIS-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-SOLEIS-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-HADNS-IIIa-2007-editedDR-QAQC-revised.sql
psql srdb -f ../spreadsheets/MINTO-NPOUTNS-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-PLAIC7d-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-PLAICIIIa-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-PLAICNS-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-POLLNS-VI-IIIa-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MINTO-SEELNS-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-COD2224-1970-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-COD2532-1966-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-HADROCK-1991-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-HER2532-1974-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-HER30-1973-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-HER31-1973-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-HERRIGA-1977-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-HKENRTN-1978-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-HKESOTH-1982-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-SPR2232-1974-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-ANEBISC-1987-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-HAD7BK-1993-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-HERVASU-1986-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-MACNEA-1972-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-MGB8C9A-1986-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-MGW8C9A-1986-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-PLECELT-1977-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-PLEECHW-1976-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-SOLBISC-1984-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-SARSOTH-1978-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-SOLCELT-1971-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-GHLARCT-1969-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-HERIRLN-1961-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-SOLECHW-1969-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-WHBCOMB-1972-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-SOLKASK-1984-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENNINGS-ICES-WHG7EK-1982-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-SMOOTHOREOWECR-2004-v2-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-SMOOTHOREOCR-2004-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-BLACKOREOWECR-2007-v2-editedDR.sql
psql srdb -f ../spreadsheets/FRANCIS-HOK1W-2007-editedDR.sql
psql srdb -f ../spreadsheets/FRANCIS-HOK1E-2007-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-SQUIREFISHNZ8-2005-v2-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-TREVALLYNZ7-2005-v2-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-GEMFISHNZ-2007-v2-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-RROCKLOBSTERCRA1-2001-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-RROCKLOBSTERCRA2-2001-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-RROCKLOBSTERCRA3-2007-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-RROCKLOBSTERCRA4-2005-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-RROCKLOBSTERCRA5-2002-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-RROCKLOBSTERCRA7-2005-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-RROCKLOBSTERCRA8-2005-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-KAHNZ-2006-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-PINKLINGNZ3-4-2007-v2-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-PINKLINGNZ5-6-2007-v2-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-PINKLINGNZ6b-2006-v2-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-PINKLINGNZ72-2007-v2-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-PINKLINGNZ7WC-2008-v2-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-SOHAKENZCR-2006-v2-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-SOHAKENZSA-2007-v2-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-BWHITINGNZCIR-2006-v2-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-BFOOTABALONENZ5A-2006-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-BFOOTABALONENZ5B-2007-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-BFOOTABALONENZ5D-2006-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-BFOOTABALONENZ7-2008-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-OROUGHYMEC-2004-v2-editedDR.sql
psql srdb -f ../spreadsheets/MELNYCHUK-SABLEFEBSAIGA-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/BRANCH-SABLEFPCOAST-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/Chute-oceanquahog-2008-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-GTRIGGM-2006-editedDR.sql
psql srdb -f ../spreadsheets/GILROY-MENHADENGM-2007-editedDR.sql
psql srdb -f ../spreadsheets/FAUCONNET-BNOSESHARATL-2007-editedDR.sql
psql srdb -f ../spreadsheets/FAUCONNET-FTOOTHSHARATL-2007-editedDR.sql
psql srdb -f ../spreadsheets/FAUCONNET-BTIPSHARATL-2006-editedDR.sql
psql srdb -f ../spreadsheets/FAUCONNET-BTIPSHARSATL-2006-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-ATLMENHADEN-editedDR.sql
psql srdb -f ../spreadsheets/COLLIE-HERRPWS-2006-editedOJ.sql
psql srdb -f ../spreadsheets/COLLIE-HERRSIT-2007-editedOJ.sql
psql srdb -f ../spreadsheets/STANTON-SouthPetraleSole-2004-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-NorthPetraleSole-2004-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-SNOWGROUPSATLC-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MELNYCHUK-PCODBSAI-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MELNYCHUK-PCODGA-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/STANTON-REXSOLEGA-2007-editedOJ-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-RKCRABBB-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-BKINGCRABSMI-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-GKINGCRABAIES-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-TANNERCRABBSAI-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-RKCRABPI-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-BKINGCRABPI-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-GKINGCRABAIWS-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-RKINGCRABNS-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-SNOWCRABBS-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/STANTON-WEAKFISHATLC-2009-v2-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-RGROUPGM-2006-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/BAUM-AMPL3LNO-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/BAUM-AMPL3M-2008-editedDR.sql
psql srdb -f ../spreadsheets/PREFONTAINE-BARNSK-2002-editedDR.sql
psql srdb -f ../spreadsheets/PREFONTAINE-COD2J3KLIS-2006-editedDR.sql
psql srdb -f ../spreadsheets/BAUM-COD3NO-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/PREFONTAINE-GHAL23KLMNO-2007-editedDR.sql
psql srdb -f ../spreadsheets/PREFONTAINE-GHAL4RST-2003-editedDR.sql
psql srdb -f ../spreadsheets/PREFONTAINE-HAD4X5Y-2003-editedDR-QAQCjb.sql
psql srdb -f ../spreadsheets/PREFONTAINE-HERR4VWX-2006-editedDR.sql
psql srdb -f ../spreadsheets/PREFONTAINE-RED1-2005-editedDR.sql
psql srdb -f ../spreadsheets/PREFONTAINE-RED3M-2007-editedDR.sql
psql srdb -f ../spreadsheets/PREFONTAINE-RED23K-2001-editedDR.sql
psql srdb -f ../spreadsheets/PREFONTAINE-RED3Pn4RSTVn-2001-editedDR.sql
psql srdb -f ../spreadsheets/BAUM-YELL3LNO-2008-editedDR.sql
psql srdb -f ../spreadsheets/PREFONTAINE-AMPL3Ps-2005-editedDR.sql
psql srdb -f ../spreadsheets/PREFONTAINE-POLL4VWX5Zc-2006-editedDR.sql
psql srdb -f ../spreadsheets/Parma-PHALCANUS-NPacific-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-MUTSNAPSATLCGM-2008-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-GAGSATLC-2006-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-GAGGM-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-VSNAPGM-2006-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-GRAMBERGM-2006-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-SPANMACKSATLC-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-ALBWPO-2008-editedDR-OJ-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-YFINCWPAC-2008-editedDR-OJ-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-SKJCWPAC-2008-editedDR-OJ-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-RPORGYSATLC-2006-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/JENSEN-KMACKSATLC-2004-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-KMACKGM-2004-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-GRAMBERSATLC-2008-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-RSNAPSATLC-2008-editedDR.sql
psql srdb -f ../spreadsheets/COLLIE-RSOLEHSTR-2001-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/COLLIE-ESOLEHSTR-2001-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/COLLIE-LOBRIDEM-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/COLLIE-WFRIDEM-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/COLLIE-TORIDEM-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/BRANCH-DKROCKPCOAST-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/BRANCH-ARFLOUNDPCOAST-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/BRANCH-BLACKROCKNPCOAST-2007-editedDR-QAQC-revised.sql
psql srdb -f ../spreadsheets/BRANCH-BLACKROCKSPCOAST-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/BRANCH-BLUEROCKCAL-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/BRANCH-COWCODSCAL-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/BRANCH-LNOSESKAPCOAST-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/BRANCH-POPERCHPCOAST-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/BRANCH-BOCACCSPCOAST-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/BRANCH-WROCKPCOAST-2007-editedDR.sql
psql srdb -f ../spreadsheets/BRANCH-YEYEROCKPCOAST-2007-editedDR.sql
psql srdb -f ../spreadsheets/BRANCH-SBELLYROCKPCOAST-2007-editedDR.sql
psql srdb -f ../spreadsheets/BRANCH-PHAKEPCOAST-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/BRANCH-CHILISPCOAST-2007-editedDR.sql
psql srdb -f ../spreadsheets/BRANCH-ESOLEPCOAST-2007-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/BRANCH-CROCKPCOAST-2007-editedDR.sql
psql srdb -f ../spreadsheets/STACHURA-CROCKPCOAST-2009-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-SRAKEROCKBSAI-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/STANTON-FLSOLEBSAI-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/STANTON-REYEROCKBSAI-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/STANTON-NRSOLEEBSAI-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/STANTON-ATKABSAI-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/STANTON-GHALBSAI-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/STANTON-NROCKBSAI-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/STANTON-PERCHEBSAI-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/STANTON-ARFLOUNDBSAI-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/STANTON-ARFLOUNDGA-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/STANTON-DSOLEWC-2005-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/STANTON-WCgopher-2005-editedDR-QAQC-longtimeseries.sql
psql srdb -f ../spreadsheets/STANTON-SouthStarryFlounder-2005-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/STANTON-NorthStarryFlounder-2005-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/STANTON-VSNAPSATLC-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MELNYCHUK-WPOLLEBS-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MELNYCHUK-ALPLAICBSAI-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/MELNYCHUK-YSOLEBSAI-2008-editedDR.sql
psql srdb -f ../spreadsheets/MELNYCHUK-WPOLLGA-2008-editedDR.sql
psql srdb -f ../spreadsheets/MELNYCHUK-NROCKGA-2008-editedDR.sql
psql srdb -f ../spreadsheets/MELNYCHUK-DUSROCKGA-2008-editedDR.sql
psql srdb -f ../spreadsheets/MELNYCHUK-WPOLLAI-2008-editedDR.sql
psql srdb -f ../spreadsheets/MELNYCHUK-POPERCHGA-2008-editedDR.sql
psql srdb -f ../spreadsheets/STACHURA-POPERCHGA-2010-editedDR.sql
psql srdb -f ../spreadsheets/MELNYCHUK-REYEROCKGA-2008-editedDR.sql
psql srdb -f ../spreadsheets/BAUM-REDFISHSPP3LN-2008-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-MATLCROAK-2004-editedDR.sql
psql srdb -f ../spreadsheets/PINSKY-SARDPCOAST-2007-editedDR.sql
psql srdb -f ../spreadsheets/PINSKY-CMACKPCOAST-2008-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-SCORPWC-2005-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-FLSOLEGA-2007-editedOJ.sql
psql srdb -f ../spreadsheets/STACHURA-FLSOLEGA-2010-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-DSOLEGA-2007-editedOJ.sql
psql srdb -f ../spreadsheets/FAUCONNET-SBARSHARATL-2006-editedDR.sql
psql srdb -f ../spreadsheets/FAUCONNET-SNOSESHARATL-2007-editedDR.sql
psql srdb -f ../spreadsheets/FAUCONNET-BHEADSHARATL-2007-editedDR.sql
psql srdb -f ../spreadsheets/FAUCONNET-SFINMAKNWPAC-2009-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-JACKMACKCH-2008-editedDR.sql
psql srdb -f ../spreadsheets/RICARD-JACKMACKCH-2010-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-YTSNAPSATLC-2003-editedDR.sql
psql srdb -f ../spreadsheets/IDOINE-NSHRIMP-2008-editedDR.sql
psql srdb -f ../spreadsheets/HART-SEASCALLOPMA-2007-editedDR.sql
psql srdb -f ../spreadsheets/HART-SEASCALLOPGB-2007-editedDR.sql
psql srdb -f ../spreadsheets/CHUTE-DEEPSEAREDCRAB-2008-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-YellowTailWC-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/STANTON-NorthLingcod-2005-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-SouthLingcod-2005-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-TILESATLC-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/STANTON-Blackgill-2005-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-Shortspine-2005-v2-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-LongspineTH-2005-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-WPOLLNSO-1997-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-WPOLLWBS-2004-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-LOBSTER5Y-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-LOBSTER5Z-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-LOBSTERSNE-editedDR.sql
psql srdb -f ../spreadsheets/BAUM-COD3M-2008-editedDR.sql
psql srdb -f ../spreadsheets/ANDERSON-CHIOSGSL-2008-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-KelpGreenling-2005-Cope2-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-Northcabezon-Cope2-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-Southcabezon-Cope2-editedDR.sql
psql srdb -f ../spreadsheets/COL-ATLHALIBUT-2008-editedDR.sql
psql srdb -f ../spreadsheets/TERCEIRO-WINFLOUNSNEMATL-2008-editedDR.sql
psql srdb -f ../spreadsheets/BAUM-YELLGB-2008-editedDR.sql
psql srdb -f ../spreadsheets/BAUM-HAD5Z-2008-editedDR.sql
psql srdb -f ../spreadsheets/PALMER-HADGOM-2008-editedDR.sql
psql srdb -f ../spreadsheets/BAUM-CODGOM-2008-rkmayo-edits-editedDR.sql
psql srdb -f ../spreadsheets/OBRIEN-APGMGB-2008-editedDR.sql
psql srdb -f ../spreadsheets/BAUM-SFLOUNMATLC-2008-editedDR.sql
psql srdb -f ../spreadsheets/LEGAULT-YELLCCGOM-2008-editedDR.sql
psql srdb -f ../spreadsheets/WIGLEY-POUT-2008-editedDR.sql
psql srdb -f ../spreadsheets/WIGLEY-WITCH-2008-editedDR.sql
psql srdb -f ../spreadsheets/LEGAULT-BAUM-YELLSNEMATL-2008-editedDR.sql
psql srdb -f ../spreadsheets/BAUM-CODGB-2008-lob-edits-editedDR.sql
psql srdb -f ../spreadsheets/RAM-HENDRICKSON-ILLEX-2005-editedDR.sql
psql srdb -f ../spreadsheets/HENDRICKSON-WINTERFLGB-2008-editedDR.sql
psql srdb -f ../spreadsheets/OVERHOLTZ-ATLMACKEREL-2005-editedDR.sql
psql srdb -f ../spreadsheets/NITSCHKE-WINTERFLGOM-2008-editedDR.sql
psql srdb -f ../spreadsheets/HENDRICKSON-WINDOWPANEGOMGB-2008-editedDR.sql
psql srdb -f ../spreadsheets/HENDRICKSON-WINDOWPANESNEMA-2008-editedDR.sql
psql srdb -f ../spreadsheets/TERCEIRO-SCUP-2008-editedDR.sql
psql srdb -f ../spreadsheets/RICHARDS-MONKFISHSGBMA-2007-editedDR.sql
psql srdb -f ../spreadsheets/RICHARDS-MONKFISHGOMNGB-2007-editedDR.sql
psql srdb -f ../spreadsheets/SOSEBEE-WHITEHAKE-2008-editedDR.sql
psql srdb -f ../spreadsheets/COL-SILVERHAKEGOMNGB-2005-editedOJ.sql
psql srdb -f ../spreadsheets/COL-SILVERHAKESGBMA-2005-editedOJ.sql
psql srdb -f ../spreadsheets/MAYO-POLLOCK-5YZ-2008-editedOJ.sql
psql srdb -f ../spreadsheets/OVERHOLTZ-ATLHERRING-2008-editedOJ.sql
psql srdb -f ../spreadsheets/OVERHOLTZ-BUTTERFISH-2003-editedOJ.sql
psql srdb -f ../spreadsheets/SHEPHERD-BLACKSEABASS-2008-editedOJ.sql
psql srdb -f ../spreadsheets/SHEPHERD-STRIPEDBASS-2007-editedDR.sql
psql srdb -f ../spreadsheets/SHEPHERD-BLUEFISH-2008-editedDR.sql
psql srdb -f ../spreadsheets/NITSCHKE-TILEFISH-2005-editedDR.sql
psql srdb -f ../spreadsheets/MILLER-ACADIANREDFISH-2008-editedDR-QAQC.sql
psql srdb -f ../spreadsheets/SOSBEE-SPINYDOGFISH-2006-editedDR.sql
psql srdb -f ../spreadsheets/SOSBEE-BARNDOORSKATE-2007-editedDR.sql
psql srdb -f ../spreadsheets/SOSBEE-CLEARNOSESKATE-2007-editedDR.sql
psql srdb -f ../spreadsheets/SOSBEE-LITTLESKATE-2007-editedDR.sql
psql srdb -f ../spreadsheets/SOSBEE-ROSETTESKATE-2007-editedDR.sql
psql srdb -f ../spreadsheets/SOSBEE-SMOOTHSKATE-2007-editedDR.sql
psql srdb -f ../spreadsheets/SOSBEE-THORNYSKATE-2007-editedDR.sql
psql srdb -f ../spreadsheets/SOSBEE-WINTERSKATE-2007-editedDR.sql
psql srdb -f ../spreadsheets/JACOBSON-ATLSURFCLAM-2008-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-RSNAPEGM-2005-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-RSNAPWGM-2005-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-ANCHOVYKILKACS-2007-editedDR.sql
psql srdb -f ../spreadsheets/RICARD-COD2J3KL-2006-editedDR.sql
psql srdb -f ../spreadsheets/Parma-SBT-2010v2-editedDR.sql
psql srdb -f ../spreadsheets/JENSEN-STMARLINSWPAC-2006-editedDR.sql
psql srdb -f ../spreadsheets/STANTON-SABLEPCOAST-editedDR.sql
psql srdb -f ../spreadsheets/FAY-PTOOTHFISHMACCA-2010-editedDR.sql
psql srdb -f ../spreadsheets/RICARD-CUSK-4X-2011.sql
